name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Extract changelog for version
      id: changelog
      run: |
        VERSION=${{ steps.version.outputs.VERSION }}
        awk "/## \[${VERSION}\]/,/## \[/" CHANGELOG.md | sed '1d;$d' > release_notes.md
        
    - name: Create release archive
      run: |
        tar -czf ubuntu-tools-server-v${{ steps.version.outputs.VERSION }}.tar.gz \
          menu.sh \
          setup-permissions.sh \
          scripts/ \
          README.md \
          QUICKSTART.md \
          CHANGELOG.md \
          CONTRIBUTING.md \
          LICENSE
          
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release v${{ steps.version.outputs.VERSION }}
        body_path: release_notes.md
        files: ubuntu-tools-server-v${{ steps.version.outputs.VERSION }}.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
