name: Shell Script Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: ShellCheck Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        severity: warning
        
  syntax-check:
    name: Bash Syntax Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check menu.sh syntax
      run: bash -n menu.sh
      
    - name: Check all scripts syntax
      run: |
        for script in scripts/*.sh; do
          echo "Checking $script..."
          bash -n "$script"
        done
        
    - name: Check setup-permissions.sh syntax
      run: bash -n setup-permissions.sh
