name: Update Version Badge

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  update-badge:
    name: Update Version in README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        
    - name: Get latest tag
      id: tag
      run: |
        git fetch --tags
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        VERSION=${LATEST_TAG#v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Update README badge
      run: |
        VERSION=${{ steps.tag.outputs.VERSION }}
        sed -i "s/Version-[0-9.]\\+-green/Version-${VERSION}-green/" README.md
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update version badge to ${{ steps.tag.outputs.VERSION }}"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
